# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogInWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogInWindow(object):
    def setupUi(self, LogInWindow):
        LogInWindow.setObjectName("LogInWindow")
        LogInWindow.setWindowModality(QtCore.Qt.NonModal)
        LogInWindow.resize(801, 345)
        LogInWindow.setMinimumSize(QtCore.QSize(50, 0))
        LogInWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.gridLayout = QtWidgets.QGridLayout(LogInWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(LogInWindow)
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setObjectName("label")
        self.label.setPixmap(QtGui.QPixmap("UI/image/edge.png"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(18, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_confirm = QtWidgets.QPushButton(LogInWindow)
        self.btn_confirm.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.541701, y1:1, x2:0.537, y2:0, stop:0.20398 rgba(51, 102, 153, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-style:none;\n"
"border:1px solid #3f3f3f; \n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;")
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout.addWidget(self.btn_confirm)
        self.btn_register = QtWidgets.QPushButton(LogInWindow)
        self.btn_register.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.541701, y1:1, x2:0.537, y2:0, stop:0.20398 rgba(51, 102, 153, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-style:none;\n"
"border:1px solid #3f3f3f; \n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;")
        self.btn_register.setObjectName("btn_register")
        self.horizontalLayout.addWidget(self.btn_register)
        self.btn_cancel = QtWidgets.QPushButton(LogInWindow)
        self.btn_cancel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.541701, y1:1, x2:0.537, y2:0, stop:0.20398 rgba(51, 102, 153, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-style:none;\n"
"border:1px solid #3f3f3f; \n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(LogInWindow)
        self.label_9.setMinimumSize(QtCore.QSize(75, 75))
        self.label_9.setMaximumSize(QtCore.QSize(75, 75))
        self.label_9.setStyleSheet("")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("UI/image/main_title.jpg"))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(13)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(LogInWindow)
        self.label_2.setMinimumSize(QtCore.QSize(60, 35))
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.user_name_lineEdit = QtWidgets.QLineEdit(LogInWindow)
        self.user_name_lineEdit.setMinimumSize(QtCore.QSize(400, 35))
        self.user_name_lineEdit.setMaximumSize(QtCore.QSize(400, 35))
        self.user_name_lineEdit.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.user_name_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.user_name_lineEdit.setClearButtonEnabled(True)
        self.user_name_lineEdit.setObjectName("user_name_lineEdit")
        self.horizontalLayout_2.addWidget(self.user_name_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(LogInWindow)
        self.label_3.setMinimumSize(QtCore.QSize(60, 35))
        self.label_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.user_password_lineEdit = QtWidgets.QLineEdit(LogInWindow)
        self.user_password_lineEdit.setMinimumSize(QtCore.QSize(400, 35))
        self.user_password_lineEdit.setMaximumSize(QtCore.QSize(400, 35))
        self.user_password_lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.user_password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.user_password_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.user_password_lineEdit.setClearButtonEnabled(True)
        self.user_password_lineEdit.setObjectName("user_password_lineEdit")
        self.horizontalLayout_3.addWidget(self.user_password_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)

        self.retranslateUi(LogInWindow)
        QtCore.QMetaObject.connectSlotsByName(LogInWindow)

    def retranslateUi(self, LogInWindow):
        _translate = QtCore.QCoreApplication.translate
        LogInWindow.setWindowTitle(_translate("LogInWindow", "登录"))
        # self.label.setText(_translate("LogInWindow", "<html><head/><body><p><img src=\":/image/edge(login).png\"/></p></body></html>"))
        self.btn_confirm.setText(_translate("LogInWindow", "确认"))
        self.btn_register.setText(_translate("LogInWindow", "注册用户"))
        self.btn_cancel.setText(_translate("LogInWindow", "取消"))
        self.label_2.setText(_translate("LogInWindow", "用户名："))
        self.user_name_lineEdit.setPlaceholderText(_translate("LogInWindow", "请输入用户名"))
        self.label_3.setText(_translate("LogInWindow", "密码："))
        self.user_password_lineEdit.setPlaceholderText(_translate("LogInWindow", "请输入密码"))
import main_rc
import qss_rc
