# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotSubWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotSubWindow(object):
    def setupUi(self, PlotSubWindow):
        PlotSubWindow.setObjectName("PlotSubWindow")
        PlotSubWindow.resize(760, 863)
        self.centralwidget = QtWidgets.QWidget(PlotSubWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 500))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(3)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout.addWidget(self.frame_5, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        PlotSubWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PlotSubWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotSubWindow)

    def retranslateUi(self, PlotSubWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotSubWindow.setWindowTitle(_translate("PlotSubWindow", "MainWindow"))
