# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotWindow(object):
    def setupUi(self, PlotWindow):
        PlotWindow.setObjectName("PlotWindow")
        PlotWindow.resize(1135, 867)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlotWindow.sizePolicy().hasHeightForWidth())
        PlotWindow.setSizePolicy(sizePolicy)
        PlotWindow.setMinimumSize(QtCore.QSize(548, 309))
        PlotWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(PlotWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/image/edge.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(325, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("font: 17pt \"Adobe 黑体 Std R\";\n"
"\n"
"color:#B4CDCD;")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setLineWidth(3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.factoryCheckBox = QtWidgets.QCheckBox(self.frame)
        self.factoryCheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.factoryCheckBox.setFont(font)
        self.factoryCheckBox.setMouseTracking(True)
        self.factoryCheckBox.setStyleSheet("")
        self.factoryCheckBox.setIconSize(QtCore.QSize(20, 20))
        self.factoryCheckBox.setChecked(False)
        self.factoryCheckBox.setObjectName("factoryCheckBox")
        self.verticalLayout.addWidget(self.factoryCheckBox)
        self.useCheckBox = QtWidgets.QCheckBox(self.frame)
        self.useCheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.useCheckBox.setFont(font)
        self.useCheckBox.setMouseTracking(True)
        self.useCheckBox.setStyleSheet("")
        self.useCheckBox.setIconSize(QtCore.QSize(20, 20))
        self.useCheckBox.setChecked(False)
        self.useCheckBox.setObjectName("useCheckBox")
        self.verticalLayout.addWidget(self.useCheckBox)
        self.tempCheckBox = QtWidgets.QCheckBox(self.frame)
        self.tempCheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tempCheckBox.setFont(font)
        self.tempCheckBox.setMouseTracking(True)
        self.tempCheckBox.setStyleSheet("")
        self.tempCheckBox.setIconSize(QtCore.QSize(20, 20))
        self.tempCheckBox.setChecked(False)
        self.tempCheckBox.setObjectName("tempCheckBox")
        self.verticalLayout.addWidget(self.tempCheckBox)
        self.businessCheckBox = QtWidgets.QCheckBox(self.frame)
        self.businessCheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.businessCheckBox.setFont(font)
        self.businessCheckBox.setMouseTracking(True)
        self.businessCheckBox.setStyleSheet("")
        self.businessCheckBox.setIconSize(QtCore.QSize(20, 20))
        self.businessCheckBox.setChecked(False)
        self.businessCheckBox.setObjectName("businessCheckBox")
        self.verticalLayout.addWidget(self.businessCheckBox)
        self.exCheckBox = QtWidgets.QCheckBox(self.frame)
        self.exCheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exCheckBox.setFont(font)
        self.exCheckBox.setMouseTracking(True)
        self.exCheckBox.setStyleSheet("")
        self.exCheckBox.setIconSize(QtCore.QSize(20, 20))
        self.exCheckBox.setChecked(False)
        self.exCheckBox.setObjectName("exCheckBox")
        self.verticalLayout.addWidget(self.exCheckBox)
        self.timeCheckBox = QtWidgets.QCheckBox(self.frame)
        self.timeCheckBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.timeCheckBox.setFont(font)
        self.timeCheckBox.setMouseTracking(True)
        self.timeCheckBox.setStyleSheet("")
        self.timeCheckBox.setIconSize(QtCore.QSize(20, 20))
        self.timeCheckBox.setChecked(False)
        self.timeCheckBox.setObjectName("timeCheckBox")
        self.verticalLayout.addWidget(self.timeCheckBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_yes = QtWidgets.QPushButton(self.frame)
        self.btn_yes.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_yes.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_yes.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.541701, y1:1, x2:0.537, y2:0, stop:0.20398 rgba(51, 102, 153, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-style:none;\n"
"border:1px solid #3f3f3f; \n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;")
        self.btn_yes.setObjectName("btn_yes")
        self.horizontalLayout.addWidget(self.btn_yes)
        self.btn_no = QtWidgets.QPushButton(self.frame)
        self.btn_no.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_no.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.541701, y1:1, x2:0.537, y2:0, stop:0.20398 rgba(51, 102, 153, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-style:none;\n"
"border:1px solid #3f3f3f; \n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;")
        self.btn_no.setObjectName("btn_no")
        self.horizontalLayout.addWidget(self.btn_no)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("font: 17pt \"Adobe 黑体 Std R\";\n"
"\n"
"color:#B4CDCD;")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setLineWidth(3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2.addWidget(self.frame)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tableView = QtWidgets.QTableView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(0, 220))
        self.tableView.setMaximumSize(QtCore.QSize(16777215, 280))
        self.tableView.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_2.addWidget(self.splitter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        PlotWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(PlotWindow)
        self.statusBar.setObjectName("statusBar")
        PlotWindow.setStatusBar(self.statusBar)

        self.retranslateUi(PlotWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlotWindow)

    def retranslateUi(self, PlotWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotWindow.setWindowTitle(_translate("PlotWindow", "MainWindow"))
        self.label_2.setText(_translate("PlotWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#145b7d;\">-------------参量待选状态---------------</span></p></body></html>"))
        self.factoryCheckBox.setText(_translate("PlotWindow", "   生产厂家"))
        self.useCheckBox.setText(_translate("PlotWindow", "   使用频率"))
        self.tempCheckBox.setText(_translate("PlotWindow", "   环境温度"))
        self.businessCheckBox.setText(_translate("PlotWindow", "    运营商"))
        self.exCheckBox.setText(_translate("PlotWindow", "   其他因素"))
        self.timeCheckBox.setText(_translate("PlotWindow", "   安装时长"))
        self.btn_yes.setText(_translate("PlotWindow", "确定"))
        self.btn_no.setText(_translate("PlotWindow", "取消"))
        self.label_3.setText(_translate("PlotWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#145b7d;\">----------------------------------------------</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PlotWindow", "Tab 1"))

import main_rc
import qss_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotWindow = QtWidgets.QMainWindow()
    ui = Ui_PlotWindow()
    ui.setupUi(PlotWindow)
    PlotWindow.show()
    sys.exit(app.exec_())

