# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotWindow(object):
    def setupUi(self, PlotWindow):
        PlotWindow.setObjectName("PlotWindow")
        PlotWindow.resize(1195, 873)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlotWindow.sizePolicy().hasHeightForWidth())
        PlotWindow.setSizePolicy(sizePolicy)
        PlotWindow.setMinimumSize(QtCore.QSize(548, 309))
        PlotWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(PlotWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.splitter_6 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_6)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(75, 75))
        self.label_9.setMaximumSize(QtCore.QSize(75, 75))
        self.label_9.setStyleSheet("image: url(:/image/main_title.png);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(750, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.splitter_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setMinimumSize(QtCore.QSize(0, 300))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("font: 17pt \"Adobe 黑体 Std R\";\n"
"\n"
"color:#B4CDCD;")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setLineWidth(3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.comboBox_type_station = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_type_station.setMinimumSize(QtCore.QSize(170, 28))
        self.comboBox_type_station.setMaximumSize(QtCore.QSize(170, 23))
        self.comboBox_type_station.setStyleSheet("background-color: rgb(180, 205, 205);")
        self.comboBox_type_station.setObjectName("comboBox_type_station")
        self.horizontalLayout_2.addWidget(self.comboBox_type_station)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.comboBox_type_pile = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_type_pile.setMinimumSize(QtCore.QSize(170, 28))
        self.comboBox_type_pile.setMaximumSize(QtCore.QSize(170, 23))
        self.comboBox_type_pile.setStyleSheet("background-color: rgb(180, 205, 205);")
        self.comboBox_type_pile.setEditable(False)
        self.comboBox_type_pile.setObjectName("comboBox_type_pile")
        self.horizontalLayout_3.addWidget(self.comboBox_type_pile)
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.comboBox_type_time = QtWidgets.QComboBox(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_type_time.sizePolicy().hasHeightForWidth())
        self.comboBox_type_time.setSizePolicy(sizePolicy)
        self.comboBox_type_time.setMinimumSize(QtCore.QSize(255, 28))
        self.comboBox_type_time.setMaximumSize(QtCore.QSize(255, 23))
        self.comboBox_type_time.setStyleSheet("background-color: rgb(180, 205, 205);")
        self.comboBox_type_time.setEditable(False)
        self.comboBox_type_time.setCurrentText("")
        self.comboBox_type_time.setMaxVisibleItems(10)
        self.comboBox_type_time.setObjectName("comboBox_type_time")
        self.horizontalLayout_4.addWidget(self.comboBox_type_time)
        self.layoutWidget4 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.comboBox_type_pie = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox_type_pie.setMinimumSize(QtCore.QSize(170, 28))
        self.comboBox_type_pie.setMaximumSize(QtCore.QSize(170, 23))
        self.comboBox_type_pie.setStyleSheet("background-color: rgb(180, 205, 205);")
        self.comboBox_type_pie.setObjectName("comboBox_type_pie")
        self.horizontalLayout_6.addWidget(self.comboBox_type_pie)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.lineCheckBox_2 = QtWidgets.QCheckBox(self.splitter)
        self.lineCheckBox_2.setEnabled(True)
        self.lineCheckBox_2.setMouseTracking(True)
        self.lineCheckBox_2.setChecked(True)
        self.lineCheckBox_2.setObjectName("lineCheckBox_2")
        self.pieCheckBox = QtWidgets.QCheckBox(self.splitter)
        self.pieCheckBox.setObjectName("pieCheckBox")
        self.verticalLayout.addWidget(self.splitter_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label_10 = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 50))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setStyleSheet("font: 17pt \"Adobe 黑体 Std R\";\n"
"\n"
"color:#B4CDCD;")
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setLineWidth(3)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.layoutWidget5 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_risk_graphy_display = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_risk_graphy_display.sizePolicy().hasHeightForWidth())
        self.btn_risk_graphy_display.setSizePolicy(sizePolicy)
        self.btn_risk_graphy_display.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_risk_graphy_display.setMaximumSize(QtCore.QSize(16777215, 51))
        self.btn_risk_graphy_display.setStyleSheet("background-color: #B4CDCD;\n"
"border-style:none;\n"
"border:1px solid #3f3f3f; \n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;")
        self.btn_risk_graphy_display.setObjectName("btn_risk_graphy_display")
        self.horizontalLayout.addWidget(self.btn_risk_graphy_display)
        spacerItem4 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.btn_plot = QtWidgets.QPushButton(self.layoutWidget5)
        self.btn_plot.setMinimumSize(QtCore.QSize(151, 32))
        self.btn_plot.setMaximumSize(QtCore.QSize(151, 51))
        self.btn_plot.setStyleSheet("background-color: rgb(180, 205, 205);\n"
"border-style:none;\n"
"border:1px solid #3f3f3f; \n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;")
        self.btn_plot.setObjectName("btn_plot")
        self.horizontalLayout.addWidget(self.btn_plot)
        self.verticalLayout.addWidget(self.splitter_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 32))
        self.label_3.setStyleSheet("font: 17pt \"Adobe 黑体 Std R\";\n"
"\n"
"color:#B4CDCD;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setMinimumSize(QtCore.QSize(0, 250))
        self.tableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tabWidget)
        PlotWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(PlotWindow)
        self.statusBar.setObjectName("statusBar")
        PlotWindow.setStatusBar(self.statusBar)
        self.toolBar_2 = QtWidgets.QToolBar(PlotWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        PlotWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar = QtWidgets.QToolBar(PlotWindow)
        self.toolBar.setObjectName("toolBar")
        PlotWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.label_6.setBuddy(self.comboBox_type_station)
        self.label_7.setBuddy(self.comboBox_type_pile)

        self.retranslateUi(PlotWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlotWindow)

    def retranslateUi(self, PlotWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotWindow.setWindowTitle(_translate("PlotWindow", "MainWindow"))
        self.label_9.setText(_translate("PlotWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_8.setText(_translate("PlotWindow", "<html><head/><body><p><span style=\" font-family:\'华文隶书\'; font-size:26pt; font-weight:600; color:#2684cb;\">北京市计量检测科学研究院</span></p></body></html>"))
        self.label_2.setText(_translate("PlotWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#b4cdcd;\">---------------数据可视化---------------</span></p></body></html>"))
        self.label_6.setText(_translate("PlotWindow", "<html><head/><body><p><span style=\" font-weight:600;\">选择充电站：</span></p></body></html>"))
        self.label_7.setText(_translate("PlotWindow", "<html><head/><body><p><span style=\" font-weight:600;\">选择充电桩：</span></p></body></html>"))
        self.label_11.setText(_translate("PlotWindow", "<html><head/><body><p><span style=\" font-weight:600;\">选择时间段：</span></p></body></html>"))
        self.label_5.setText(_translate("PlotWindow", "<html><head/><body><p><span style=\" font-weight:600;\">画图种类：</span></p></body></html>"))
        self.label.setText(_translate("PlotWindow", "<html><head/><body><p><span style=\" font-weight:600;\">图片类型：</span></p></body></html>"))
        self.lineCheckBox_2.setText(_translate("PlotWindow", "折线图"))
        self.pieCheckBox.setText(_translate("PlotWindow", "饼状图"))
        self.label_10.setText(_translate("PlotWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#b4cdcd;\">-------------------风险等级-------------------</span></p></body></html>"))
        self.btn_risk_graphy_display.setText(_translate("PlotWindow", "充电站区域分布展示"))
        self.btn_plot.setText(_translate("PlotWindow", "绘制"))
        self.label_3.setText(_translate("PlotWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#b4cdcd;\">-----------当前充电站统计数据：-----------</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PlotWindow", "Tab 1"))
        self.toolBar_2.setWindowTitle(_translate("PlotWindow", "toolBar_2"))
        self.toolBar.setWindowTitle(_translate("PlotWindow", "toolBar"))

import main_rc
import qss_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotWindow = QtWidgets.QMainWindow()
    ui = Ui_PlotWindow()
    ui.setupUi(PlotWindow)
    PlotWindow.show()
    sys.exit(app.exec_())

