# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SigninWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SigninDialog(object):
    def setupUi(self, SigninDialog):
        SigninDialog.setObjectName("SigninDialog")
        SigninDialog.resize(749, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SigninDialog.sizePolicy().hasHeightForWidth())
        SigninDialog.setSizePolicy(sizePolicy)
        SigninDialog.setMinimumSize(QtCore.QSize(555, 410))
        SigninDialog.setStyleSheet("")
        self.label_8 = QtWidgets.QLabel(SigninDialog)
        self.label_8.setGeometry(QtCore.QRect(38, 11, 656, 100))
        self.label_8.setMinimumSize(QtCore.QSize(0, 100))
        self.label_8.setStyleSheet("border-image: url(:/image/edge.png);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(SigninDialog)
        self.label_9.setGeometry(QtCore.QRect(40, 200, 75, 75))
        self.label_9.setMinimumSize(QtCore.QSize(75, 75))
        self.label_9.setMaximumSize(QtCore.QSize(75, 75))
        self.label_9.setStyleSheet("image: url(:/image/main_title.jpg);")
        self.label_9.setObjectName("label_9")
        self.splitter_7 = QtWidgets.QSplitter(SigninDialog)
        self.splitter_7.setGeometry(QtCore.QRect(150, 130, 449, 301))
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.splitter = QtWidgets.QSplitter(self.splitter_7)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_5 = QtWidgets.QLabel(self.splitter)
        self.label_5.setMinimumSize(QtCore.QSize(47, 19))
        self.label_5.setStyleSheet("color: #000000")
        self.label_5.setObjectName("label_5")
        self.real_name_lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.real_name_lineEdit.setMinimumSize(QtCore.QSize(140, 19))
        self.real_name_lineEdit.setStyleSheet("color:#000000")
        self.real_name_lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.real_name_lineEdit.setClearButtonEnabled(True)
        self.real_name_lineEdit.setObjectName("real_name_lineEdit")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label = QtWidgets.QLabel(self.splitter_4)
        self.label.setMinimumSize(QtCore.QSize(47, 19))
        self.label.setMaximumSize(QtCore.QSize(96, 16777215))
        self.label.setStyleSheet("color: rgb(0, 0, 0)")
        self.label.setObjectName("label")
        self.name_lineEdit = QtWidgets.QLineEdit(self.splitter_4)
        self.name_lineEdit.setMinimumSize(QtCore.QSize(140, 19))
        self.name_lineEdit.setStyleSheet("color: #000000")
        self.name_lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.name_lineEdit.setClearButtonEnabled(True)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setMinimumSize(QtCore.QSize(47, 19))
        self.label_2.setStyleSheet("color: #000000")
        self.label_2.setObjectName("label_2")
        self.password_lineEdit = QtWidgets.QLineEdit(self.splitter_2)
        self.password_lineEdit.setMinimumSize(QtCore.QSize(140, 19))
        self.password_lineEdit.setStyleSheet("color:#000000")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password_lineEdit.setClearButtonEnabled(True)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_4 = QtWidgets.QLabel(self.splitter_3)
        self.label_4.setMinimumSize(QtCore.QSize(47, 19))
        self.label_4.setMaximumSize(QtCore.QSize(96, 16777215))
        self.label_4.setStyleSheet("color: #000000")
        self.label_4.setObjectName("label_4")
        self.check_password_lineEdit = QtWidgets.QLineEdit(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_password_lineEdit.sizePolicy().hasHeightForWidth())
        self.check_password_lineEdit.setSizePolicy(sizePolicy)
        self.check_password_lineEdit.setMinimumSize(QtCore.QSize(302, 24))
        self.check_password_lineEdit.setMaximumSize(QtCore.QSize(347, 16777215))
        self.check_password_lineEdit.setStyleSheet("color: #000000\n"
"")
        self.check_password_lineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.check_password_lineEdit.setClearButtonEnabled(True)
        self.check_password_lineEdit.setObjectName("check_password_lineEdit")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.label_7 = QtWidgets.QLabel(self.splitter_6)
        self.label_7.setMinimumSize(QtCore.QSize(47, 19))
        self.label_7.setStyleSheet("color: #000000")
        self.label_7.setObjectName("label_7")
        self.department_lineEdit = QtWidgets.QLineEdit(self.splitter_6)
        self.department_lineEdit.setMinimumSize(QtCore.QSize(140, 19))
        self.department_lineEdit.setMaximumSize(QtCore.QSize(347, 16777215))
        self.department_lineEdit.setStyleSheet("color:#000000")
        self.department_lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.department_lineEdit.setClearButtonEnabled(True)
        self.department_lineEdit.setObjectName("department_lineEdit")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_6 = QtWidgets.QLabel(self.splitter_5)
        self.label_6.setMinimumSize(QtCore.QSize(47, 19))
        self.label_6.setStyleSheet("color: #000000")
        self.label_6.setObjectName("label_6")
        self.telephone_lineEdit = QtWidgets.QLineEdit(self.splitter_5)
        self.telephone_lineEdit.setMinimumSize(QtCore.QSize(140, 19))
        self.telephone_lineEdit.setStyleSheet("color:#000000")
        self.telephone_lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.telephone_lineEdit.setClearButtonEnabled(True)
        self.telephone_lineEdit.setObjectName("telephone_lineEdit")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.btn_confirm_2 = QtWidgets.QPushButton(self.splitter_8)
        self.btn_confirm_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.541701, y1:1, x2:0.537, y2:0, stop:0.20398 rgba(51, 102, 153, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-style:none;\n"
"border:1px solid #3f3f3f; \n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;")
        self.btn_confirm_2.setObjectName("btn_confirm_2")
        self.btn_cancel = QtWidgets.QPushButton(self.splitter_8)
        self.btn_cancel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.541701, y1:1, x2:0.537, y2:0, stop:0.20398 rgba(51, 102, 153, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-style:none;\n"
"border:1px solid #3f3f3f; \n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;")
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(SigninDialog)
        QtCore.QMetaObject.connectSlotsByName(SigninDialog)

    def retranslateUi(self, SigninDialog):
        _translate = QtCore.QCoreApplication.translate
        SigninDialog.setWindowTitle(_translate("SigninDialog", "Dialog"))
        self.label_8.setText(_translate("SigninDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:40px; font-weight:600; color:#ffffff; background-color:transparent;\">北京市计量检测科学研究院用户注册</span></p></body></html>"))
        self.label_9.setText(_translate("SigninDialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("SigninDialog", "姓名:"))
        self.real_name_lineEdit.setPlaceholderText(_translate("SigninDialog", "姓名"))
        self.label.setText(_translate("SigninDialog", "用户名:"))
        self.name_lineEdit.setPlaceholderText(_translate("SigninDialog", "用户名"))
        self.label_2.setText(_translate("SigninDialog", "密码:"))
        self.password_lineEdit.setPlaceholderText(_translate("SigninDialog", "用户密码"))
        self.label_4.setText(_translate("SigninDialog", "重复密码:"))
        self.check_password_lineEdit.setPlaceholderText(_translate("SigninDialog", "确认用户密码"))
        self.label_7.setText(_translate("SigninDialog", "部门："))
        self.department_lineEdit.setPlaceholderText(_translate("SigninDialog", "部门"))
        self.label_6.setText(_translate("SigninDialog", "电话："))
        self.telephone_lineEdit.setPlaceholderText(_translate("SigninDialog", "电话"))
        self.btn_confirm_2.setText(_translate("SigninDialog", "确认"))
        self.btn_cancel.setText(_translate("SigninDialog", "取消"))
import main_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SigninDialog = QtWidgets.QDialog()
    ui = Ui_SigninDialog()
    ui.setupUi(SigninDialog)
    SigninDialog.show()
    sys.exit(app.exec_())

