# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserManageWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageWindow(object):
    def setupUi(self, ManageWindow):
        ManageWindow.setObjectName("ManageWindow")
        ManageWindow.resize(904, 826)
        ManageWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(ManageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(75, 75))
        self.label_9.setMaximumSize(QtCore.QSize(75, 75))
        self.label_9.setStyleSheet("image: url(:/image/main_title.png);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 20pt \"华文隶书\";\n"
"color: rgb(0, 0, 0);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_save = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_save.setMinimumSize(QtCore.QSize(0, 38))
        self.btn_save.setStyleSheet("background-color:rgb(40, 140, 212);\n"
"font: 10pt \"Adobe Arabic\";")
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.btn_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_delete.setMinimumSize(QtCore.QSize(0, 38))
        self.btn_delete.setStyleSheet("background-color: rgb(40, 140, 212);\n"
"font: 10pt \"Adobe Arabic\";")
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.btn_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_reset.setMinimumSize(QtCore.QSize(0, 38))
        self.btn_reset.setStyleSheet("background-color: rgb(40, 140, 212);\n"
"font: 10pt \"Adobe Arabic\";")
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout.addWidget(self.btn_reset)
        self.btn_quit = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_quit.setMinimumSize(QtCore.QSize(0, 38))
        self.btn_quit.setStyleSheet("background-color:rgb(40, 140, 212);\n"
"font: 10pt \"Adobe Arabic\";")
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout.addWidget(self.btn_quit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(self.layoutWidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.splitter)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(0, 85))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 85))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_8)
        ManageWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ManageWindow)
        self.statusbar.setObjectName("statusbar")
        ManageWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ManageWindow)
        QtCore.QMetaObject.connectSlotsByName(ManageWindow)

    def retranslateUi(self, ManageWindow):
        _translate = QtCore.QCoreApplication.translate
        ManageWindow.setWindowTitle(_translate("ManageWindow", "MainWindow"))
        self.label_9.setText(_translate("ManageWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("ManageWindow", "<html><head/><body><p><span style=\" font-size:24pt; color:#2684cb;\">用户管理</span></p></body></html>"))
        self.btn_save.setText(_translate("ManageWindow", "保存"))
        self.btn_delete.setText(_translate("ManageWindow", "删除"))
        self.btn_reset.setText(_translate("ManageWindow", "重置"))
        self.btn_quit.setText(_translate("ManageWindow", "退出"))
        self.label_8.setText(_translate("ManageWindow", "<html><head/><body><p><span style=\" font-family:\'华文隶书\'; font-size:26pt; font-weight:600; color:#ffffff;\">------</span><span style=\" font-family:\'华文隶书\'; font-size:26pt; font-weight:600; color:#2684cb;\">北京市计量检测科学研究院 </span><span style=\" font-family:\'华文隶书\'; font-size:26pt; font-weight:600; color:#ffffff;\">-----</span></p></body></html>"))
import main_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManageWindow = QtWidgets.QMainWindow()
    ui = Ui_ManageWindow()
    ui.setupUi(ManageWindow)
    ManageWindow.show()
    sys.exit(app.exec_())

